# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./nidesso-frontend/package-lock.json"
        
    - run: npm i
      working-directory: ./nidesso-frontend
        
    - run: npm run build
      working-directory: ./nidesso-frontend
      
    - run: |
           mkdir tmp

           cp nidesso-frontend/build/index.html nidesso-frontend/build/404.html
           cp -r nidesso-frontend/build/* ./tmp

           git pull --all
           git checkout -f build/gh-page
           git branch

           rm -r $( printf '%s\n' * | grep -Ewv ".git|tmp" )

           mv tmp/* ./
           rm -r tmp 

           touch CNAME
           echo "www.nidesso.ch" >> CNAME

           git config --global user.email "build@nidesso.ch"
           git config --global user.name "Build Job"
           git add .
           git commit -m "build by github action" --allow-empty
           git push


      
